server:
  port:
database:
  user:
  password:
  host:
  dbName:
  port:
  sslMode:
  timeZone:
  maxIdleTime:
  maxIdleConns:
  maxOpenConns:
  conMaxLifetime:
logger:
  log_level:
  file_name:
  path:
  dev_mode:
  max_size:
  max_backups:
  max_age:
  compress:
